# Generated by Django 4.1.7 on 2023-04-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('informacoes', models.CharField(max_length=300)),
                ('cargos', models.CharField(max_length=70)),
            ],
        ),
    ]
