# Generated by Django 4.1.7 on 2023-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0003_alter_reuniao_cargos_alter_reuniao_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='cargos',
            field=models.CharField(blank=True, choices=[(1, 'Cargo 1'), (2, 'Cargo 2'), (3, 'Cargo 3')], max_length=255, null=True),
        ),
    ]
