# Generated by Django 4.1.7 on 2023-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0004_alter_reuniao_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='cargos',
            field=models.CharField(max_length=100),
        ),
    ]
