# Generated by Django 4.1.7 on 2023-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField(verbose_name='Data da consulta (00/00/0000   00:00)')),
                ('horario', models.CharField(max_length=20)),
                ('informacoes', models.CharField(max_length=200)),
            ],
        ),
    ]
