# Generated by Django 4.1.7 on 2023-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(verbose_name='Data do evento (00/00/0000   00:00)'),
        ),
    ]
