# Generated by Django 4.1.7 on 2023-04-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_evento_horario_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='informacoes',
            field=models.CharField(max_length=200, verbose_name='Informações'),
        ),
    ]
