# Generated by Django 4.1.7 on 2023-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='informacoes',
            field=models.TextField(verbose_name='Informações'),
        ),
    ]
