# Generated by Django 4.1.7 on 2023-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cadastro_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cargo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
